In [1]:
import sys
from pathlib import Path
import pandas as pd

ROOT = Path("..").resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from Quantreo.DataPreprocessing import *

data_file = ROOT / "Data" / "FixTimeBars" / "GBPUSD_1H_Demo_READY.csv"

df = pd.read_csv(data_file, index_col="time", parse_dates=True)

print("Rows:", len(df))
print("Columns:", df.columns.tolist())

df.head()

Rows: 8341
Columns: ['open', 'high', 'low', 'close', 'tick_volume', 'spread', 'real_volume', 'low_time', 'high_time']

,open,high,low,close,tick_volume,spread,real_volume,low_time,high_time
time,,,,,,,,,
2025-05-30 03:00:00,1.34982,1.35087,1.34893,1.34956,3113,18,0,2025-05-30 03:50:00,2025-05-30 03:25:00
2025-05-30 04:00:00,1.34956,1.35099,1.34792,1.34811,3571,18,0,2025-05-30 04:55:00,2025-05-30 04:20:00
2025-05-30 05:00:00,1.34811,1.34855,1.34699,1.34717,2660,18,0,2025-05-30 05:50:00,2025-05-30 05:00:00
2025-05-30 06:00:00,1.34717,1.34785,1.34674,1.34699,1932,18,0,2025-05-30 06:55:00,2025-05-30 06:10:00
2025-05-30 07:00:00,1.34699,1.34745,1.34687,1.34705,1929,18,0,2025-05-30 07:05:00,2025-05-30 07:25:00

In [2]:
df = sma(df, "close", 20)
df = sma(df, "close", 50)
df = rsi(df, "close", 14)
df = bollinger(df, "close", 20)

In [3]:
# Simple Moving Averages
df = sma(df, "close", 20)
df = sma(df, "close", 50)

# Relative Strength Index
df = rsi(df, "close", 14)

# Bollinger Bands (20-period, 2 standard deviations)
df = bollinger(df, "close", 20)

print("Updated columns:")
print(df.columns.tolist())

df.tail()

Updated columns:
['open', 'high', 'low', 'close', 'tick_volume', 'spread', 'real_volume', 'low_time', 'high_time', 'SMA_20', 'SMA_50', 'RSI']

,open,high,low,close,tick_volume,spread,real_volume,low_time,high_time,SMA_20,SMA_50,RSI
time,,,,,,,,,,,,
2026-10-02 11:00:00,1.32135,1.32218,1.32022,1.32078,13971,0,0,2026-10-02 11:45:00,2026-10-02 11:05:00,1.320050,1.323571,47.647207
2026-10-02 12:00:00,1.32078,1.32155,1.32020,1.32114,11058,0,0,2026-10-02 12:05:00,2026-10-02 12:20:00,1.319931,1.323466,49.655107
2026-10-02 13:00:00,1.32114,1.32135,1.31998,1.32069,15693,0,0,2026-10-02 13:20:00,2026-10-02 13:00:00,1.319908,1.323329,47.217307
2026-10-02 14:00:00,1.32069,1.32136,1.32021,1.32063,12413,0,0,2026-10-02 14:00:00,2026-10-02 14:40:00,1.319970,1.323181,46.886779
2026-10-02 15:00:00,1.32063,1.32431,1.31961,1.32320,35725,0,0,2026-10-02 15:15:00,2026-10-02 15:30:00,1.320206,1.323057,59.851038

In [9]:
print(df[["close"]].tail())

print("\nMissing values:")
print(df.isna().sum())

                       close
time
2026-10-02 11:00:00  1.32078
2026-10-02 12:00:00  1.32114
2026-10-02 13:00:00  1.32069
2026-10-02 14:00:00  1.32063
2026-10-02 15:00:00  1.32320

Missing values:
open            0
high            0
low             0
close           0
tick_volume     0
spread          0
real_volume     0
low_time        5
high_time       5
SMA_20         19
SMA_50         49
RSI            13
dtype: int64

In [10]:
output_file = Path("../Data/EURUSD_H1_FEATURES.csv")
df.to_csv(output_file, index=False)

print("Saved to:", output_file)

Saved to: ../Data/EURUSD_H1_FEATURES.csv

In [ ]:
print("Rows:", len(df))
print("Columns:", df.columns.tolist())

# Check whether the indicators were added
df.tail()

Rows: 8341
Columns: ['open', 'high', 'low', 'close', 'tick_volume', 'spread', 'real_volume', 'low_time', 'high_time', 'SMA_20', 'SMA_50', 'RSI']

,open,high,low,close,tick_volume,spread,real_volume,low_time,high_time,SMA_20,SMA_50,RSI
time,,,,,,,,,,,,
2026-10-02 11:00:00,1.32135,1.32218,1.32022,1.32078,13971,0,0,2026-10-02 11:45:00,2026-10-02 11:05:00,1.320050,1.323571,47.647207
2026-10-02 12:00:00,1.32078,1.32155,1.32020,1.32114,11058,0,0,2026-10-02 12:05:00,2026-10-02 12:20:00,1.319931,1.323466,49.655107
2026-10-02 13:00:00,1.32114,1.32135,1.31998,1.32069,15693,0,0,2026-10-02 13:20:00,2026-10-02 13:00:00,1.319908,1.323329,47.217307
2026-10-02 14:00:00,1.32069,1.32136,1.32021,1.32063,12413,0,0,2026-10-02 14:00:00,2026-10-02 14:40:00,1.319970,1.323181,46.886779
2026-10-02 15:00:00,1.32063,1.32431,1.31961,1.32320,35725,0,0,2026-10-02 15:15:00,2026-10-02 15:30:00,1.320206,1.323057,59.851038

: